theme: jekyll-theme-minimal
title: "Mi portfolio"
description: "Soy estudiante de segundo año de la carrera de Ciencia de Datos e Inteligencia Artificial, con el objetivo de hacer una transición hacia el ámbito de TI y análisis de datos. "
logo: "assets/img/foto corporativa 2025 2.jpg"
github:
  is_project_page: false
